### ISSUE TITLE
Make GPUModel specific to TensorRT

### ISSUE THREAD

**Issue by jeremyfowers** [groq/mlagility#10]
Right now benchit has a class called GPUModel. However, it is actually specific to TensorRT and nvidia GPUs. Clean up the code to reflect this (for example, rename it to TRTModel or something).

**Comment by jeremyfowers** [comment]
@ramkrishna2910 what do you think the scope is here? Do we just need to rename GPUModel to TRTModel?

**Comment by ramkrishna2910** [comment]
Will take a look at this today.
