### ISSUE TITLE
Implement the benchit --runtime feature

### ISSUE THREAD

**Issue by jeremyfowers** [groq/mlagility#12]
Right now the --runtime flag is ignored in the CLI and nonexistent in the API. Implement it according to the description in the benchit user guide.

Note that this will be very simple right now since there is a 1:1 correlation between devices and runtimes.

**Comment by jeremyfowers** [comment]
Depends on #11 and #10

**Comment by jeremyfowers** [comment]
I'm going to push this feature out of the first release. Justification is that we aren't going to put any runtime options into the first release, so this wont do much until later. 

I'll do a small PR to putting a "coming soon" tag on the `--runtime` feature in the docs.

cc @ramkrishna2910 @danielholanda

**Comment by ramkrishna2910** [comment]
Relates to #87

**Comment by jeremyfowers** [comment]
> Relates to #87

Yep - let's say the same PR should implement both this and #87
