### ISSUE TITLE
The number of parameters of a given model are only computed when device is "groq"

### ISSUE THREAD

**Issue by danielholanda** [groq/mlagility#151]
**Issue:**

The number of parameters of a given model are only computed when device is "groq".

**Task:**

Ensure that the number of parameters is saved to the state file regardless of the device.

**Comment by danielholanda** [comment]
@jeremyfowers for visibility

**Comment by jeremyfowers** [comment]
The parameters are being computed, they just aren't being saved. Proof:

```
(mla) jfowers@jfowers:~/mlagility$ benchit examples/cli/scripts/hello_world.py --analyze-only --device x86

Models discovered during profiling:

hello_world.py:
        pytorch_model (executed 1x - 0.10s)
                Model Type:     Pytorch (torch.nn.Module)
                Class:          SmallModel (<class 'hello_world.SmallModel'>)
                Location:       /home/jfowers/mlagility/examples/cli/scripts/hello_world.py, line 29
                Parameters:     55 (<0.1 MB)
                Hash:           479b1332

pytorch_outputs: tensor([-0.1675,  0.1548, -0.1627,  0.0067,  0.3353], grad_fn=<AddBackward0>)

Woohoo! The 'benchmark' command is complete.
```

**Comment by jeremyfowers** [comment]
This is a wrinkle... but a solvable one! analysis.py gets the parameter count, but has no notion of `State` so it doesn't save the parameter count to state. Meanwhile, GroqFlow also gets the parameter count, but only saves it during the *Compile* Stage (why there, and not during Export, I do not know...).

But we can call the helper function that groqflow.justgroqit.compile is using!

https://github.com/groq/groqflow/blob/bb06ed0e3c6ea87947d9c393b19a73036031337b/groqflow/justgroqit/compile.py#L14

**Comment by jeremyfowers** [comment]
#154 will solve this for now. In the long term, if we want to support Pytorch as a runtime (which would not involve any ONNX file at all) we will probably want `analysis.py` to be able to create a State file and put vital info into it.
