### ISSUE TITLE
MLAgility stats should not go into GroqFlow state.yaml

### ISSUE THREAD

**Issue by jeremyfowers** [groq/mlagility#157]
There are too many quirks to state.yaml that mlagility does not have control over. Put mlagility stats into a dedicated mlagility_stats.yaml file.

Also, update report.py to take advantage of mlagility_stats.yaml.

**Comment by danielholanda** [comment]
Solved by https://github.com/groq/mlagility/pull/160 and https://github.com/groq/mlagility/pull/188
