### ISSUE TITLE
`benchit` gets stuck forever on certain models

### ISSUE THREAD

**Issue by danielholanda** [groq/mlagility#171]
**Description:** 

`Benchit` has no time-out feature. As a result, `benchit` will get stuck if the process of benchmarking any of the models gets stuck.

This issue was observed when running all of mlagility benchmarks on x86. During that process `mlagility/models/transformers/luke.py` was stuck on `Optimizing Model` for hours while using 0% of all CPUs.

**Comment by jeremyfowers** [comment]
Yeah we should probably add a per-stage timeout. 10-15 mins should be sufficient for everything except Groq Compiler.

**Comment by jeremyfowers** [comment]
BTW optimizing model is called for all 3 devices so this bug is probably not specific to x86 in any way?

**Comment by danielholanda** [comment]
> BTW optimizing model is called for all 3 devices so this bug is probably not specific to x86 in any way?

I'm not aware of any reason to believe that this bug is specific to x86.

> Yeah we should probably add a per-stage timeout. 10-15 mins should be sufficient for everything except Groq Compiler.

Agreed.

Just for context, all slurm jobs already have a global timeout of 2h so this issue currently doesn't happen on slurm jobs.

on `slurm.py`
```
 slurm_command.extend(
        [
            "--time=00-02:00:00",  # days-hh:mm:ss"
            f"--job-name={job_name}",
...
```

**Comment by jeremyfowers** [comment]
Ok nice @danielholanda. Just a quick note that stages are defined in GroqFlow so if we want a per-stage timeout we would have to do it there. We could put an e2e timeout in mlagility itself but that would need to be much more coarse grained (1 hour? 2 hours?) and could waste a lot of time.

**Comment by jeremyfowers** [comment]
Taking a quick look at this issue and `luke.py` built and benchmarked successfully with me in under 5 minutes

```
(mla) jfowers@jfowers:~/mlagility$ benchit models/transformers/luke.py 

Models discovered during profiling:

luke.py:
        model (executed 1x)
                Model Type:     Pytorch (torch.nn.Module)
                Class:          LukeModel (<class 'transformers.models.luke.modeling_luke.LukeModel'>)
                Location:       /home/jfowers/mlagility/models/transformers/luke.py, line 15
                Parameters:     274,500,608 (523.6 MB)
                Hash:           431c265c
                Status:         Computing...




Building "luke_transformers_431c265c"
    ✓ Exporting PyTorch to ONNX   
    ✓ Optimizing ONNX file   
    ✓ Converting to FP16   
    ✓ Finishing up   

Woohoo! Saved to ~/.cache/mlagility/luke_transformers_431c265c
```

I wonder what caused it to hang for you @danielholanda? Could be non-deterministic or I could be on a different package(s) versions than you. Any idea how to deterministically reproduce?

I could always make my own model and put `sleep(10^10)` in the forward function 😹
