### ISSUE TITLE
MLAgility support for ONNX models

### ISSUE THREAD

**Issue by jeremyfowers** [groq/mlagility#18]
Current behavior: MLAgility `benchit` and `benchmark_script()` tools only accept `.py` scripts as input. However, a user might have a `.onnx` file they want to use as input. 

Desired solution: Allow a `.onnx` file with static input shapes and control flow to be a valid input to `benchit`. 

Considerations:
- `benchmark_script()` is literally supposed to take a script and benchmark the models within it. It doesn't make sense to support `.onnx` files as an input to `benchmark_script()` since `.onnx` is not a script.
- So the `.onnx` file should go straight into `benchmark_model()`, however:
  - `benchmark_model()` requires both a model and inputs as arguments, while a `.onnx` file is just a model
  - So a wrapper function should call `onnxflow.api.run_ort_model.dummy_inputs()` to get some dummy inputs and pass them into `benchmark_model()`
  - There is no path from `benchit` into `benchmark_model()` right now. So we need a wrapper function that looks at the input argument and then calls either `benchmark_model()` or `benchmark_script()` as appropriate
     - This introduces one additional nit: right now `benchit` takes `INPUT_SCRIPT` as a positional arg. Which means that `INPUT_SCRIPT` needs to change to `INPUT_FILE` or there needs to be a new command like `benchit benchmark onnx INPUT_FILE`. I prefer the former.

**Comment by jeremyfowers** [comment]
fyi @danielholanda I'm taking a crack at this

**Comment by jeremyfowers** [comment]
Bumping up the priority because Groq needs this internally.

**Comment by jeremyfowers** [comment]
Added implementation ideas to the description.

**Comment by danielholanda** [comment]
Implementation plan seems sound!

**Comment by ramkrishna2910** [comment]
Plan sounds good.
