### ISSUE TITLE
Streamlit page should load critical info from report.csv

### ISSUE THREAD

**Issue by jeremyfowers** [groq/mlagility#189]
Problem: items like the following are hardcoded into `app.py`: 

> Intel(R) Xeon(R) X40 CPU @ 2.00GHz on Google Cloud (custom: n2, 80 vCPU, 64.00 GiB) and OnnxRuntime version 1.14.0

Info like the OnnxRuntime version will change over time. Our credibility will be seriously impacted if we ever forget to update one of these version numbers on the page.

Proposed solution: critical information such as device names, package version numbers, etc. should be recorded into report.csv (or other file on disk). The streamlit page then loads these values dynamically to make sure they are never out of date.

Labeling as mid-priority because we don't need it for the initial release, but we should have this before we start frequently updating the data.

cc @danielholanda @kovtcharov

**Comment by ramkrishna2910** [comment]
All of this information is populated in the `output.json` for each run. We can pull this data from the generated json file for accurate information.
