### ISSUE TITLE
`x86/nvidia` initial stages are different from `groq`, causing issues when generating the report

### ISSUE THREAD

**Issue by danielholanda** [groq/mlagility#195]
GroqFlow checks whether all operations are supported before converting models to FP16. As a result, the same model might convert to FP16 when the device is `x86`/`nvidia`, but will not convert to FP16 when the device is `groq` when not all ops are supported by GroqFlow. 

This behavior will be flagged as a warning when running `benchit cache report`. 

The ability to export/optimize/convert to fp16 for the `retinanet_resnet50_fpn` model is shown below to illustrate this issue.

 |        | Export | Optimize | Convert to FP16 |
|--------|--------|----------|-----------------|
| groq   |   ✓     | ✓         | ×                |
| x86    |    ✓     | ✓         | ✓                |

**Comment by danielholanda** [comment]
for vis @jeremyfowers

**Comment by jeremyfowers** [comment]
Proposed solution: manually set the build Sequence for groqit() to:
1. Export to PyTorch
2. Optimize
3. Convert to fp16
4. Check ops
5. Compile
6. Assemble

I don't see any reason why this wouldnt function correctly.

**Comment by danielholanda** [comment]
I agree that the proposed solution is reasonable.
