### ISSUE TITLE
Loosely defined requirements allow for mismatches between environments

### ISSUE THREAD

**Issue by danielholanda** [groq/mlagility#196]
Although the same `requirements.txt` file is installed in all environments, they might still end up with different packages that might affect the creation of the ONNX file. The table below shows some of the main differences found between some of our environments.

| groq env | trt/ort env | 
|--------|----------|
| onnx==1.11.0 | onnx==1.13.1 |
| onnxconverter-common==1.12.1 | onnxconverter-common==1.13.0|
| torch==1.13.0 | torch==1.13.1|
| transformers==4.24.0 | transformers==4.22.1|

**Comment by danielholanda** [comment]
@jeremyfowers for vis

**Comment by jeremyfowers** [comment]
@danielholanda is that groq environment from GroqFlow 2.5.2 or 3.0.2? The GroqFlow 3.0.2 environment is a lot more relaxed.

**Comment by jeremyfowers** [comment]
Here's the deps for 3.0.2:

```
install_requires=[
        "onnx>=1.11.0",
        "onnxmltools==1.10.0",
        "hummingbird-ml==0.4.4",
        "scikit-learn==1.1.1",
        "xgboost==1.6.1",
        "onnxruntime>=1.10.0",
        "paramiko==2.11.0",
        "torch>=1.12.1",
        "protobuf>=3.17.3",
        "pyyaml>=5.4",
        "typeguard>=2.3.13",
        "packaging>=21.3",
    ],
```

**Comment by danielholanda** [comment]
Our curerrent GroqFlow results use `groqflow_version: 3.0.2`

**Comment by jeremyfowers** [comment]
Ok I think its groq SDK 0.9.2 that's forcing us on to ONNX 0.11.0 then. There isn't really anything we can do about that. 

Personally I think its fine to use the versions of OSS tools that the down-stack vendor tools support. It's part of the turnkey compatibility story - does your vendor's tool support the latest and greatest of OSS or not?

**Comment by jeremyfowers** [comment]
Possible solution:
- `setup.py` continues to have loosely-defined requirements, to allow for maximum user flexibility when benchmarking their own model
- `models/requirements.txt` locks down exact version numbers for every package to guarantee total consistency when performing the benchmark
   - Or, if that's too restrictive for some reason, could add a new file called something like `models/hard_requirements.txt` that locks down every package version
