### ISSUE TITLE
Sometimes `export MLAGILITY_TRACEBACK=True` does not show error log

### ISSUE THREAD

**Issue by jcwchen** [groq/mlagility#213]
I am playing with the benchit CLI these days. Thank you for this amazing work! It's exciting to see the performance result for so many state-of-art models.

I have tried several models under this repo and the result looks good. The error can be printed out if I bumped into issues while running `benchit`. However, when I used `benchit models/torchvision/fasterrcnn_resnet50_fpn.py`, the output is as follows:
```
Models discovered during profiling:

fasterrcnn_resnet50_fpn.py:
        model (executed 1x)
                Model Type:     Pytorch (torch.nn.Module)
                Class:          FasterRCNN (<class 'torchvision.models.detection.faster_rcnn.FasterRCNN'>)
                Location:       /home/xxx/miniconda3/envs/mla/lib/python3.8/site-packages/torchvision/models/detection/faster_rcnn.py, line 570
                Parameters:     41,755,286 (79.6 MB)
                Hash:           d8b3f65a
                Status:         Build Error: see log files for details.
                                To see the full stack trace, rerun with `export MLAGILITY_TRACEBACK=True`.


Woohoo! The 'benchmark' command is complete.
```
I have set `export MLAGILITY_TRACEBACK=True`, but I still cannot see the full error log. Did I missing something? Thanks for looking into it.

Another nit suggestion: https://github.com/groq/mlagility/tree/main/examples/cli is a great entry point for new benchit CLI users. Perhaps having a real-world model example (any model under `mlagility/models/`) in the [readme.md](https://github.com/groq/mlagility/tree/main/examples/cli#readme) would be very helpful and impressive.

**Comment by ramkrishna2910** [comment]
Hi @jcwchen 
Thank you for reaching out.
With `export MLAGILITY_TRACEBACK=True`, I was able to get the stack trace of the error as follows:
![image](https://user-images.githubusercontent.com/12814146/226764993-664995d5-cd3b-4b45-9baa-dbea555969f9.png)
Can you please check if you are on the latest version of `main`?

Thank you for the suggestion on the readme. We will take a look :)

**Comment by jeremyfowers** [comment]
Hey @jcwchen thanks for reaching out! You made me realize that we probably want to display the traceback by default, rather than making the user set an environment variable.

I'm not sure if this will fix your specific issue, but I have opened a PR to change the default behavior: https://github.com/groq/mlagility/pull/215. This should make things more convenient in the future.

**Comment by jeremyfowers** [comment]
Also I like your suggestion about the tutorial and opened #216 to add it to the backlog.

**Comment by jeremyfowers** [comment]
> Hey @jcwchen thanks for reaching out! You made me realize that we probably want to display the traceback by default, rather than making the user set an environment variable.
> 
> I'm not sure if this will fix your specific issue, but I have opened a PR to change the default behavior: #215. This should make things more convenient in the future.

@jcwchen #215 is merged, can you pull main and try again?

**Comment by jcwchen** [comment]
> @jcwchen https://github.com/groq/mlagility/pull/215 is merged, can you pull main and try again?

Thank you both for the quick response and update! I have pulled the latest main branch and now the error log can be printed out fully. I like the idea that enabling MLAGILITY_TRACEBACK=True by default, at least at the current development stage. I will close this issue.
