### ISSUE TITLE
Handle models with the same name more robustly

### ISSUE THREAD

**Issue by danielholanda** [groq/mlagility#231]
**Issue:**

We current have a few models with the same name inside the models folder. In order to avoid `build_name` collisions our we added the author to the build_name:

`<script_name>_<author>_<hash>`, when the script has an author as part of its labels
`<script_name>_<hash>`, when the script does not have an author as part of its labels

The key issue of this approach is that we might still have a naming collision if `<script_name1>_<author>` is equals to `<script_name2>`

**Task:**

Handle models with the same way more robustly

**Comment by jeremyfowers** [comment]
Should this be "Handle models with the same `name` more robustly"?
