### ISSUE TITLE
Models readme

### ISSUE THREAD

**Issue by jeremyfowers** [groq/mlagility#24]
Add a descriptive readme.md file to `models` explaining the organization of the corpora, structure of a model file, etc.

**Comment by danielholanda** [comment]
Please add the following explanation about labels:

```
Labels must be in the first line of a Python file and start with "# labels: "
Each label must have the format "key::value1,value2,..."

 Example:
     "# labels: author::google test_group::daily,monthly"
```

**Comment by danielholanda** [comment]
Please also document the valid args in `models/readme.md`. Information about the valid args can be found in `parser.py`
