### ISSUE TITLE
benchit "export only" option

### ISSUE THREAD

**Issue by jeremyfowers** [groq/mlagility#301]
New option for CLI/API that performs only the pytorch export and no other build steps.

Design decision: add a new `--export-only` argument, or revamp the `--build-only` argument to be more flexible? The reason is because we already have `--analyze-only` and `--build-only` so it feels like clutter to add `--export-only` as well. 

For example, 
- `--build-only export` could modify `--build-only` to only run certain stages
- `--enable-phases` replaces `--build-only` and `--analyze-only` and takes a list of actions from the user. The list can include any of the following, and has all of them by default: `analyze`, `export`, `optimize`, `fp16`, `benchmark`. If the user excludes any action from the list then it gets excluded by benchit at runtime.
   - ie, Export-only functionality would be achieved with `benchit model.py --enable-phases analyze export`

cc @danielholanda @ramkrishna2910

**Comment by jeremyfowers** [comment]
Complication with `--enable-phase`: what about custom sequences? One way to deal with it would be to also just fold `--sequence-file` into the phases, for example:

```
benchit model.py --enable-phases analyze my_sequence.py benchmark` would analyze, then run whatever sequence is defined in `my_sequence.py`, then benchmark.

**Comment by ramkrishna2910** [comment]
I prefer adding `--export-only`. This does increase the number of flags we have but its clear what each flag does. `--enable-phases <options>` could get confusing and raise more questions around ordering of flags etc.

**Comment by jeremyfowers** [comment]
> I prefer adding `--export-only`. This does increase the number of flags we have but its clear what each flag does. `--enable-phases <options>` could get confusing and raise more questions around ordering of flags etc.

yeah I kinda feel that way too... plus one simple new flag is way less coding effort...

if we keep adding more flags we will have to do a big flag cleanup eventually (just not right now)

**Comment by danielholanda** [comment]
I agree that `--export-only` is the simplest option for now.

**Comment by jeremyfowers** [comment]
@danielholanda @ramkrishna2910 one more quick design decision:

- [ ] Option A: `--export-only` stops the build after the `Export Stage` (ie, `--export-only` is a subset of `--build-only`). This is the simple option for users.
- [ ] Option B: `--export-only` is not mutually exclusive with benchmarking (ie, `--export-only --build-only` will produce an ONNX file with no benchmark. But `--export-only` by itself will produce a vanilla ONNX file and then benchmark it). This is the complex-but-powerful option for users.

They have equal implementation complexity.
