### ISSUE TITLE
Models with the same graph but different inputs have the same hash

### ISSUE THREAD

**Issue by jeremyfowers** [groq/mlagility#316]
EDIT: I had the cause of the problem wrong in the original copy

For example, LLaMA with KV-caching enabled vs. disabled has the same compute graph, and therefore the same mlagility `hash`. However, those two invocations of LLaMA have completely different compute because the input shapes are completely different (the former has 1D inputs and the latter has 2D inputs). So they should have different mlagility hashes and appear separately in the `benchit` status.

Giving the two ONNX graphs different model weights does not help the problem because weights are not considered in mlagility hashing.

cc @danielholanda @ramkrishna2910

**Comment by jeremyfowers** [comment]
Proposed fix: consider model's inputs when coming up with the hash:

```
if hash_inputs:
            hashable_inputs = str(model.graph.input)
            hashable_model = hashable_model + hashable_inputs
```

**Comment by danielholanda** [comment]
I agree that taking the shape of model inputs into account when calculating the hash.

Note: The temporary solution could be potentially dangerous, since the same model might be detected multiple times when weights are loaded/changed. Not sure if we have a way of avoiding that.
