### ISSUE TITLE
Allow the user to specify a remote benchmarking IP address

### ISSUE THREAD

**Issue by jeremyfowers** [groq/mlagility#6]
Right now, the target machine for remote benchmarking is decided on a per-device basis (e.g., one machine each for x86, nvidia, and groq). Target machines are saved into a config.yaml file. If the user's config.yaml file is missing a machine for a device type, they are asked to provide a machine on the command line. If there is already a machine for that device type in config.yaml then that machine is always used.

However, a user might want to sweep over multiple accelerators each hosted on different machines (e.g., a machine for nvidia A100, a machine for nvidia H100, etc.). Right now a user would have to delete their config.yaml file in order to change machines, which is a rather cumbersome UX.

Proposed solution: implement a --ip` option for the CLI and `ip=` argument for the API would allow the user to specify an IP address at runtime.

> --ip IP is the ip address where the device can be located.
>  - Defaults to localhost, indicating the device is installed on the local machine.
>  - Typically, this will point to a remote VM where a target device is installed.
>  - Also available as API arguments: benchmark_script(ip=...), benchmark_model(ip=...).
```

**Comment by jeremyfowers** [comment]
Wait for #52

**Comment by ramkrishna2910** [comment]
There are some complications in our internal systems due to sft. So we use only ASA names now. We need to test on public networks as well before enabling this feature.

**Comment by jeremyfowers** [comment]
Yeah it seems unlikely that an external user would use the remote device support until we sort that out. Do you think we should just take the remote support out of the first release? (or call it a "beta" or something?)

**Comment by jeremyfowers** [comment]
Updated to reflect our new plans around remote benchmarking. Removing from the first release. cc @danielholanda
