### ISSUE TITLE
Add support for benchmarking multiple folders on the search path

### ISSUE THREAD

**Issue by jeremyfowers** [groq/mlagility#77]
Today `benchit --all --search-dir X` will benchmark all models in all scripts in directory X. However, MLAgility has directory of directories of models. It would be nice to benchmark all of that in one shot.

Proposed solution: support a wildcard operator, `benchit --all --search-dir X/*`, which would benchmark all models within X and all subdirectories of X. 

@danielholanda mentioned the `glob` library might be helpful for this.

**Comment by danielholanda** [comment]
After some discussion with @jeremyfowers we realized that a cleaner API for supporting the benchmarking of multiple folders is the following:

* Remove the `--all` flag
* Remove the `search_dir` argument
* Make input a positional arg which can either be a directory or script

Examples:
`benchit models/selftest/linear.py`
`benchit models/selftest/*`
`benchit models/*`
