### ISSUE TITLE
The status monitor should print script results in the order it evaluates those scripts

### ISSUE THREAD

**Issue by jeremyfowers** [groq/mlagility#85]
If you run `benchit benchmark --all -s examples/cli` it evaluates the 4 scripts in the order:
1. two_models
2. max_depth
3. keras
4. hello_world

But the final results are printed in the order:
1. hello_world
2. two_models
3. max_depth
4. keras

This is pretty confusing UX so we should fix it. I don't get why it is happening though, since dict.keys() is ordered and we print the status update by iterating over dict.keys().

**Comment by jeremyfowers** [comment]
@danielholanda any idea why this is happening?

**Comment by danielholanda** [comment]
> @danielholanda any idea why this is happening?
Not really. I agree this is weird. The standard dict type should maintain insertion order by default.
Also agree that this is a P2 issue.
