### ISSUE TITLE
Model identification can't distinguish between some models from each other

### ISSUE THREAD

**Issue by danielholanda** [groq/mlagility#86]
The goal of the analysis step is to identify all unique models within a given script. We consider two models distinct from each other if they have a different architecture.

However, there is a risk that two models with the same architecture will be instantiated within the same script, causing our model identification to fail or produce wrong results. 

The example above shows `linear.py` slightly modified.

```
# Model and input configurations
input_features_len = 10
output_features_len = 10
model_a = LinearTestModel(input_features_len, output_features_len)
model_b = LinearTestModel(input_features_len, output_features_len)
inputs = {"x": torch.rand(input_features_len)}

# Call model
model_b(**inputs)
```

Note that although `model_b` is executed, `analysis`  reports that `model_a` was executed.

```
Models found while running 'linear'

model_a (executed 1x - 0.00s)
        Model Type:     Pytorch (torch.nn.Module)
        Class:          LinearTestModel (<class 'linear.LinearTestModel'>)
        Location:       /net/home/dhnoronha/mlagility/models/selftest/linear.py, line 22
        Parameters:     110 (<0.1 MB)
        Hash:           d5b1df11
```

We consider two models distinct from each other if they have a different architecture AND they correspond to different instantiations of a class.

**Comment by danielholanda** [comment]
@jeremyfowers for vis

**Comment by jeremyfowers** [comment]
@danielholanda this seems like a corner case that most people wont hit. Suggest bumping it down to `p2` unless it starts causing someone a headache.
