### ISSUE TITLE
Enable OnnxRuntime to use execution providers for benchmarking.

### ISSUE THREAD

**Issue by ramkrishna2910** [groq/mlagility#87]
ONNX Runtime works with different hardware acceleration libraries through its extensible[ Execution Providers (EP) ](https://onnxruntime.ai/docs/execution-providers/) framework to optimally execute the ONNX models on the hardware platform. 
Currently, mlagility only supports the default execution provider (CPU/ MLAS). Ability to use the other EPs can broaden the spectrum for benchmarking.

**Comment by ramkrishna2910** [comment]
The following is the list of all available onnxruntime execution providers
<img width="752" alt="image" src="https://user-images.githubusercontent.com/12814146/221649032-e98bd6ed-2c06-4b32-a135-3f68c234b4c2.png">
The focus of this MR is going to be on adding support for:
- NVIDIA CUDA
- AMD ROCm
- Intel OpenVino

**Comment by jeremyfowers** [comment]
@ramkrishna2910 how hard is it to add one of the ARM approaches in there?

**Comment by ramkrishna2910** [comment]
None of the ARM EPs listed here has a pypi package ready to deploy.
We will have to build onnxruntime from source within the container we plan to deploy. The downside is the initial setup time for building from source will be ~15-20 mins.

**Comment by jeremyfowers** [comment]
Let's say we took that install-from-source as a manual step. And provisioning an ARM server on AWS or Azure as a manual step. Any difficulty beyond that?

**Comment by ramkrishna2910** [comment]
Nope. Provisioning and install from source are the long poles. The other parts of the pipeline are pretty straightforward.
