### ISSUE TITLE
Better API documentation

### ISSUE THREAD

**Issue by jeremyfowers** [groq/mlagility#97]
I propose the following changes:
- `benchmark_script()` becomes an official top-level API
  - add it to the top-level init.py
  - document it in the benchit user guide
  - move it to the API folder
- Rename the `benchit` API to `benchmark_model`
  - More descriptive about what it does
  - Disambiguates from the `benchit` CLI, which has a very different feature set
  - Matches the naming scheme of `benchmark_script`

@danielholanda thoughts?

**Comment by jeremyfowers** [comment]
Discussed with @danielholanda, it will be done!

**Comment by danielholanda** [comment]
Agreed that this is a great clarification to make.

`slurm.py` also has a `slurm.run_benchit` that should become `slurm.benchmark_script`.

**Comment by jeremyfowers** [comment]
> `slurm.py` also has a `slurm.run_benchit` that should become `slurm.benchmark_script`.

@danielholanda actually that is running the benchit CLI, so it's still `run_benchit` 😸
